Create Thoth schema updated command
AICoE/sefkhet-abwy pull request #185
Opened 2021-11-11 16:32 UTC by fridex

## Related Issues and Dependencies

Related: https://github.com/AICoE/sefkhet-abwy/issues/184

## This introduces a breaking change

- [x] No

2021-11-11 16:32 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **goern** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @goern` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=AICoE%2Fsefkhet-abwy).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/AICoE/sefkhet-abwy/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["goern"]} -->

2021-11-11 16:32 UTC, fridex commented
/deploy

2021-11-17 14:14 UTC, harshad16 approved these changes
lgtm
thanks :100:

2021-11-17 14:14 UTC, harshad16 commented
/test all

2021-11-17 14:14 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/AICoE/sefkhet-abwy/pull/185#pullrequestreview-808645165" title="Approved">harshad16</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=AICoE%2Fsefkhet-abwy).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/AICoE/sefkhet-abwy/blob/master/OWNERS)~~ [harshad16]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-11-17 14:17 UTC, sesheta commented
@fridex: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pre-commit | 17ca340836ea05af68029329c85798249af41dcc | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/AICoE_sefkhet-abwy/185/pre-commit/1460974762468577280) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=AICoE&repo=sefkhet-abwy&pr=185). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Afridex). Please help us and [open an issue](https://github.com/AICoE/sefkhet-abwy/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-02-15 15:28 UTC, sesheta commented
Issues go stale after 90d of inactivity.
Mark the issue as fresh with `/remove-lifecycle stale`.
Stale issues rot after an additional 30d of inactivity and eventually close.

If this issue is safe to close now please do so with `/close`.

/lifecycle stale

2022-02-20 23:24 UTC, codificat requested changes
There is a merge conflict to fix and a missing docstring that pre-commit is complaining about

2022-02-20 23:24 UTC, codificat commented on aicoe/sesheta/actions/chat.py
> +async def make_kebechet_update_issue(repo_name: str) -> str:
pre-commit is complaining of a missing docstring here

2022-03-22 23:27 UTC, sesheta commented
Stale issues rot after 30d of inactivity.
Mark the issue as fresh with `/remove-lifecycle rotten`.
Rotten issues close after an additional 30d of inactivity.

If this issue is safe to close now please do so with `/close`.

/lifecycle rotten

2022-04-22 02:09 UTC, sesheta commented
Rotten issues close after 30d of inactivity.
Reopen the issue with `/reopen`.
Mark the issue as fresh with `/remove-lifecycle rotten`.

/close

2022-04-22 02:09 UTC, sesheta commented
@sesheta: Closed this PR.

<details>

In response to [this](https://github.com/AICoE/sefkhet-abwy/pull/185#issuecomment-1105930735):

>Rotten issues close after 30d of inactivity.
>Reopen the issue with `/reopen`.
>Mark the issue as fresh with `/remove-lifecycle rotten`.
>
>/close


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-06-03 18:39 UTC, harshad16 commented
/remove-lifecycle rotten
/lgtm
/approve

Thank you :100:

2022-06-03 18:39 UTC, merged

2022-06-03 18:40 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/AICoE/sefkhet-abwy/pull/185#issuecomment-1146256346" title="Approved">harshad16</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=AICoE%2Fsefkhet-abwy).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/AICoE/sefkhet-abwy/blob/master/OWNERS)~~ [harshad16]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-06-03 18:43 UTC, sesheta commented
@fridex: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pre-commit | 2eb3e59d088975c3097a64227fcc794dfe952cf7 | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/AICoE_sefkhet-abwy/185/pre-commit/1532793861540155392) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=AICoE&repo=sefkhet-abwy&pr=185). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Afridex). Please help us and [open an issue](https://github.com/AICoE/sefkhet-abwy/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->